image: corise/dbt-course-gitpod
tasks:
  - init: |
      ./gitpod-init.sh
  - command: |
      ./gitpod-command.sh
    env:
      PGPASSWORD: gitpod
      PGDATABASE: dbt
ports:
  - port: 8000
    onOpen: open-preview
  - port: 5432
    onOpen: ignore
